spring.application.name=hrp-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret-key=1234567890abcdefghij1234567890ab

decorator.datasource.p6spy.log-format="\ntime:%(executionTime) || sql:%(sql)\n"
decorator.datasource.p6spy.logging=custom
decorator.datasource.p6spy.custom-appender-class=com.dave.hrpbackend.config.StdoutLogger
